server:
  port: ":8080"
  service_name: "ticketing-service"
  env: "dev"

database:
  host: "localhost"
  port: 5432
  user: "user"
  password: "password"
  dbname: "ticket_db"
  sslmode: "disable"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
